### ISSUE TITLE
How to use an exec path with spaces

### ISSUE THREAD

**Issue by shivenBajpai** [jiri-otoupal/pycrosskit#53]
Im trying to create a shortcut to "C:\Program Files (x86)\Slay\Slay.exe" (Slay being the name of my program)
But on running the following code

```
from pycrosskit.shortcuts import Shortcut

Shortcut(shortcut_name="Slay", exec_path="C:\\Program Files (x86)\\Slay\\Slay.exe", description="Slay",
         icon_path="C:\\Program Files (x86)\\Slay\\icon.ico", work_dir="C:\\Program Files (x86)\\Slay", desktop=True, start_menu=False)
```

What happens is that it creates a shortcut with the execution target set to
`"C:\Program Files (x86)\Slay\Slay.exe" Files(x86)\Slay\Slay.exe`
Whereas I would want
`"C:\Program Files (x86)\Slay\Slay.exe"`

Running on windows 11 python 3.10.6

**Comment by shivenBajpai** [comment]
@jiri-otoupal
Is this project still being maintained or nope?
I can submit a PR with a fix if it is

**Comment by jiri-otoupal** [comment]
Hello, yes Im sorry just did not had time to reply last week. Will get to it today.

**Comment by jiri-otoupal** [comment]
You can submit a PR request for sure will be happy to review 😊

**Comment by shivenBajpai** [comment]
Hey Im done making the fixes and wrote a test for it too, Everything works fine
Found another critical bug in your code as well
Was going to commit to my clone before opening a PR
But I can't seem to commit 
your pre-commit hook is giving out errors and I don't know how to interpret it 
Could you help?

Heres the output on vscode's git terminal

```
2023-06-15 17:47:30.387 [info] [INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pycqa/isort.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/pycqa/flake8.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Shiven\\.cache\\pre-commit\\repoh43nvwxn\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\shiven\.cache\pre-commit\repoh43nvwxn
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
      
      [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Shiven\.cache\pre-commit\repoh43nvwxn\py_env-python3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Shiven\.cache\pre-commit\repoh43nvwxn\py_env-python3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Shiven\.cache\pre-commit\repoh43nvwxn\py_env-python3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Shiven\AppData\Local\Temp\pip-build-env-o1fc6xwz\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 41, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "C:\Users\Shiven\AppData\Local\Temp\pip-build-env-o1fc6xwz\overlay\Lib\site-packages\poetry\core\factory.py", line 58, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
      
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    Encountered error while generating package metadata.
    
    See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at C:\Users\Shiven\.cache\pre-commit\pre-commit.log
```

Heres the contents of the log file mentioned at the end of that 

[pre-commit.log](https://github.com/jiri-otoupal/pycrosskit/files/11757430/pre-commit.log)

**Comment by shivenBajpai** [comment]
Nvm fixed it
